# ~/Projects/Note-Taking/Non-Fiction/Textbooks/calculus-metric-version-9e-stewart-clegg-watson
# /en/01-functions/exercise-01/org/exercise-01.org

#+LATEX_CLASS: scrbook-org
#+begin_export latex
\onehalfspacing
\recalctypearea
\mainmatter
#+end_export

* Calculus, Metric Version (9th Edition) by James Stewart, Daniel Clegg, and Saleem Watson
:PROPERTIES:
:UNNUMBERED: t
:END:

** Exercise No. 1
#+begin_export latex
  \begin{EnumerateQuestions}
  \item[1.] Let \(f\) be the function whose graph is given
    \begin{EnumerateSubquestions}
      \item Estimate the value of \(f(2)\).
      \item Estimate the values of \(x\) such that \(f(x) = 3\).
      \item State the domain of \(f\).
      \item State the range of \(f\).
      \item On what interval is \(f\) increasing?
      \item Is \(f\) even, odd, or neither even nor odd? Explain.
    \end{EnumerateSubquestions}
  \end{EnumerateQuestions}
#+end_export

** Answer to Exercise No. 1
#+begin_export latex
  \begin{EnumerateQuestions}
    \item[1.]

    \begin{EnumerateSubquestions}
      \item \(f(2) \approx \num{2.7}\)
      \item Estimate the values of \(x\) such that \(f(x) = 3\).
      \item State the domain of \(f\).
      \item State the range of \(f\).
      \item On what interval is \(f\) increasing?
      \item Is \(f\) even, odd, or neither even nor odd? Explain.
    \end{EnumerateSubquestions}
  \end{EnumerateQuestions}
#+end_export

** Exercise No. 2
#+begin_export latex
  \begin{EnumerateQuestions}
    \item[2.] Determine whether each curve is the graph of a function of \(x\).
       If it is, state the domain and range of the function.
  \end{EnumerateQuestions}
#+end_export

** Answer to Exercise No. 2
#+begin_export latex
  \begin{EnumerateQuestions}
    \item[2.]
  \end{EnumerateQuestions}
#+end_export

** Exercise No. 3
#+begin_export latex
  \begin{EnumerateQuestions}
    \item[3.] If \(f(x) = x^2 - 2x + 3\), evaluate the difference quotient
     \[\frac{f(a + h) - f(a)}{h}.\]
  \end{EnumerateQuestions}
#+end_export

** Answer to Exercise No. 3
#+begin_export latex
  \begin{EnumerateQuestions}
    \item[3.]
  \end{EnumerateQuestions}
#+end_export

** Exercise No. 4
#+begin_export latex
  \begin{EnumerateQuestions}
    \item[4.] Sketch a rough graph of the yield of a crop as a function of  the amount of fertilizer used.
  \end{EnumerateQuestions}
#+end_export

** Answer to Exercise No. 4
#+begin_export latex
  \begin{EnumerateQuestions}
    \item[4.]
  \end{EnumerateQuestions}
#+end_export

** Exercise No. 5–8

** Answer to Exercise No. 5–8

** Exercise No. 

** Answer to Exercise No. 

